name: 'Chromatic Publish'
# https://github.com/chromaui/action
# https://www.chromatic.com/docs/github-actions

on: pull_request # Avoids passing Chromatic's snapshots threshold

jobs:
  test:
    defaults:
      run:
        working-directory: quasar

    strategy:
      fail-fast: false
      matrix:
        node-version: [ 16 ]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # https://github.com/actions/setup-node#caching-global-packages-data
      - uses: actions/setup-node@v3
        with:
          # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#multiple-operating-systems-and-architectures
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: quasar/yarn.lock

      - name: yarn install
        run: yarn install --immutable
        if: ${{ github.actor != 'dependabot[bot]' && github.actor != 'renovate[bot]' }}

      - uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          workingDir: quasar
        if: ${{ github.actor != 'dependabot[bot]' && github.actor != 'renovate[bot]' }}
