name: 'Chromatic Publish'
# https://github.com/chromaui/action
# https://www.chromatic.com/docs/github-actions

on: pull_request # Avoids passing Chromatic's snapshots threshold

# https://stackoverflow.com/a/72408109/2714285
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    # Disable chromatic push during Renovate's updates
    if: ${{ github.actor != 'dependabot[bot]' && github.actor != 'renovate[bot]' }}
    defaults:
      run:
        working-directory: quasar

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to retrieve git history

      # https://github.com/renovatebot/renovate/issues/7716#issuecomment-734391360
      - name: Read Node.js version from .nvmrc
        run: echo "NODE_VERSION=$(cat ../.nvmrc)" >> $GITHUB_OUTPUT
        id: nvm

      # https://github.com/actions/setup-node#caching-global-packages-data
      - uses: actions/setup-node@v3
        with:
          # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#multiple-operating-systems-and-architectures
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
          cache: 'yarn'
          cache-dependency-path: quasar/yarn.lock

      - name: yarn install
        run: yarn install --immutable

      - uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          workingDir: quasar
