name: Tests Front - Quasar Build

on: [push, pull_request]

jobs:
  test:

    timeout-minutes: 5
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./quasar

    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3

    # https://github.com/renovatebot/renovate/issues/7716#issuecomment-843239292
    - name: Read Node.js version from package.json
      run: echo ::set-output name=nodeVersion::$(node -p "require('./package.json').engines.node")
      id: engines

    # https://github.com/actions/setup-node#caching-global-packages-data
    - uses: actions/setup-node@v3
      with:
        # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#multiple-operating-systems-and-architectures
        node-version: ${{ steps.engines.outputs.nodeVersion }}
        cache: 'yarn'
        cache-dependency-path: quasar/yarn.lock

    - name: yarn install
      run: yarn install --immutable

    - name: quasar build
      run: yarn quasar build


