name: Tests Front - e2e - Storybook

on: [push, merge_group]


# https://stackoverflow.com/a/72408109/2714285
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:

    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: ./quasar

    steps:
    - uses: actions/checkout@v4

    # https://github.com/renovatebot/renovate/issues/7716#issuecomment-734391360
    - name: Read Node.js version from .nvmrc
      run: echo "NODE_VERSION=$(cat ../.nvmrc)" >> $GITHUB_OUTPUT
      id: nvm

    # https://github.com/actions/setup-node#caching-global-packages-data
    - uses: actions/setup-node@v3
      with:
        # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#multiple-operating-systems-and-architectures
        node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
        cache: 'yarn'
        cache-dependency-path: quasar/yarn.lock

    - name: yarn install
      run: yarn install --immutable

    - name: Build Storybook
      run: yarn build-storybook

    # https://storybook.js.org/tutorials/ui-testing-handbook/react/en/automate/
    - name: Serve Storybook and run tests
      run: |
        npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
          "npx http-server storybook-static --port 6006" \
          "npx wait-on tcp:6006 && yarn test:storybook:coverage"


